menu: #站点右上角导航栏
  Home: /
  Archives: /archives
  About: /about
  rss: /atom.xml #生成RSS

widgets: #站点右边栏
- search
- category
- tagcloud

excerpt_link: Read More #阅读全文

#twitter:
#  username:
#  show_replies: false
#  tweet_count: 5

addthis: #SNS分享
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true #图片效果，默认

google_analytics:

#comment_provider: facebook
# Facebook comment
#facebook:
#  appid: 123456789012345
#  comment_count: 5
#  comment_width: 840
#  comment_colorscheme: light
